### ISSUE TITLE
Broken

### ISSUE THREAD

**Issue by sferich888** [rxcomm/weeText#3]
The underlying dependency(python-googlevoice-0.5-9.fc21.noarch, for me on Fedora), has some known issue, https://github.com/pettazz/pygooglevoice/issues/1#issuecomment-73294557, explaining that authentication is broken, making this script not work.

**Comment by rxcomm** [comment]
I don't think the python-googlevoice in the packages works. Install https://github.com/rxcomm/pygooglevoice - this one works (has some patches for the authentication issues).
